# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: verysecret
      MARIADB_DATABASE: demostack
      MARIADB_USER: db_user
      MARIADB_PASSWORD: changethis
    # volumes:
    #   - app-db-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    depends_on:
      - db
    env_file:
      - .deb.env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      - SMTP_HOST=${SMTP_HOST}
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}

# volumes:
#   app-db-data:
