# Use root/example as user/password credentials
version: "3.8"

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: verysecret
      MARIADB_DATABASE: demostack
      MARIADB_USER: db_user
      MARIADB_PASSWORD: changethis
      # TZ: "Asia/Tokyo"
      # BIND-ADDRESS: 0.0.0.0
    ports:
      - 3306:3306
    volumes:
    - db-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    environment: 
      ADMINER_PLUGINS: 'tables-filter tinymce'
      # ADMINER_DESIGN: nette
    depends_on:
      - db
    ports:
      - 9001:8080

  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    depends_on:
      - db
    env_file: .dev.env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      - SMTP_HOST=${SMTP_HOST}
    ports:
      - 8000:8000

volumes:
  db-data:
